---
editor_options: 
  markdown: 
    wrap: 72
---

library(arules) 
library(hms) 
library(readxl) 
library(ggplot2)
library(dplyr) 
library(ggstatsplot) 
library(magrittr) 
library(gt)
library(lubridate) 
library(gtsummary) 
library(summarytools)
library(qwraps2) 
library(kableExtra)

```{r}
# Cel projektu

```

```{r}
# Czyszczenie i walidacja danych
library(readxl) 
dane <- read.csv("agencja_nieruchomosci.csv")
View(dane) 
# ilość braków danych dla poszczególnych zmiennych
data.frame(braki = sapply(dane, function(x) sum(is.na(x)))) 
# w danych nie występują braki

#weryfikacja outlierów dla ceny zależej od powierzchni

plot(dane$area, dane$price, main="Rozrzut cen vs. powierzchnia", xlab="Powierzchnia", ylab="Cena") 
outliers <- boxplot(dane$price ~ dane$area, plot=FALSE)$out
# Wyświetlenie wartości odstających
if (length(outliers) > 0) {
  cat("Wartości odstające dla ceny:\n")
  print(outliers)
} else {
  cat("Brak wartości odstających dla ceny.\n")
}

#wyszły wartości odstające dla cen: #9240000 2345000 1750000 6650000 6160000 8890000 6405000 5033000 8400000 9681000 4690000 2870000 9100000
# wartości te mogą być odstające ze zwględu na inne udogodnienia jak klimatyzacja, dostęp do głównej drogi itp więc nie możemy wykluczyć ich z dalszej analizy
```
# sprawdzamy czy w danych występują duplikaty
```{r}
dane <- unique(dane) 
# nie występują
```

```{r}
#sprawdzamy czy cena nie jest gdzies ujemna 
negative_prices <- dane[dane$price < 0, ] 
View(negative_prices)
```

```{r}

# sprawdzanie korelacji między danymi

# Konwersja zmiennych kategorycznych na numeryczne

dane$mainroad <- as.numeric(dane$mainroad == "yes")
dane$guestroom <- as.numeric(dane$guestroom == "yes")
dane$basement <- as.numeric(dane$basement == "yes")
dane$hotwaterheating <- as.numeric(dane$hotwaterheating == "yes")
dane$airconditioning <- as.numeric(dane$airconditioning == "yes")
dane$prefarea <- as.numeric(dane$prefarea == "yes")
dane$furnishingstatus <- as.numeric(factor(dane$furnishingstatus, levels= c("unfurnished", "semi-furnished", "furnished")))

correlation_matrix <- cor(dane) 
print(correlation_matrix)

install.packages("corrplot") 
library(corrplot)
corrplot(correlation_matrix, method="circle") 
# najwększe korelacje występują między ceną a ilościa łazienek, powierzchnią lub klimatyzacją. Trochę mniejsze między ilością sypialni, stories bądź iloscią miejsc parkingowych a ceną

```


```{r}
#obliczenie ceny za metr 
dane$cena_na_metr <- dane$price / dane$area

#analiza częstości występowania zmiennych kategorycznych - "udogodnień"
# Częstość dostępu do drogi
table(dane$mainroad)
# Średnia cena dla dostępu do drogi
aggregate(dane$price, by = list(dane$mainroad), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od dostępu do drogi
boxplot(dane$price ~ dane$mainroad, main="Ceny w zależności od dostępu do drogi", xlab="Dostęp do drogi", ylab="Cena", col="lightblue")
```

```{r}

# Częstość preferowanej okolicy
table(dane$prefarea)
# Średnia cena dla preferowanej okolicy
aggregate(dane$price, by = list(dane$prefarea), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od preferowanej okolicy
boxplot(dane$price ~ dane$prefarea, main="Ceny w zależności od preferowanej okolicy", xlab="Preferowana okolica", ylab="Cena", col="lightgreen")
```


```{r}
# Częstość posiadania piwnicy
table(dane$basement)
# Średnia cena dla posiadania piwnicy
aggregate(dane$price, by = list(dane$basement), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od posiadania piwnicy
boxplot(dane$price ~ dane$basement, main="Ceny w zależności od posiadania piwnicy", xlab="Posiadanie piwnicy", ylab="Cena", col="lightcoral")
```

```{r}
# Częstość posiadania klimatyzacji
table(dane$airconditioning)
# Średnia cena dla posiadania klimatyzacji
aggregate(dane$price, by = list(dane$airconditioning), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od posiadania klimatyzacji
boxplot(dane$price ~ dane$airconditioning, main="Ceny w zależności od klimatyzacji", xlab="Klimatyzacja", ylab="Cena", col="lightyellow")
```

```{r}
# Częstość posiadania miejsc parkingowych
table(dane$parking)
# Średnia cena dla posiadania miejsc parkingowych
aggregate(dane$price, by = list(dane$parking), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od posiadania miejsc parkingowych
boxplot(dane$price ~ dane$parking, main="Ceny w zależności od miejsc parkingowych", xlab="Miejsca parkingowe", ylab="Cena", col="lightblue")
```

```{r}
# Częstość statusu umeblowania
table(dane$furnishingstatus)
# Średnia cena dla różnych statusów umeblowania
aggregate(dane$price, by = list(dane$furnishingstatus), FUN = mean)
# Wykres pudełkowy dla ceny w zależności od statusu umeblowania
boxplot(dane$price ~ dane$furnishingstatus, main="Ceny w zależności od statusu umeblowania", xlab="Status umeblowania", ylab="Cena", col="lightgreen")

```

```{r}
# Utworzenie ramki danych z średnimi cenami dla różnych kategorii

# Utworzenie ramki danych z średnimi cenami dla różnych kategorii
avg_prices <- aggregate(dane$price, by = list(dane$mainroad, dane$prefarea, dane$basement, dane$hotwaterheating, dane$airconditioning, dane$parking, dane$furnishingstatus), FUN = mean)
# Nadanie odpowiednich nazw kolumn w ramce danych
colnames(avg_prices) <- c("mainroad", "prefarea", "basement", "hotwaterheating", "airconditioning", "parking", "furnishingstatus", "avg_price")
# Wykres słupkowy grupowy
library(ggplot2)
ggplot(avg_prices, aes(x = mainroad, y = avg_price, fill = prefarea)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(. ~ basement + hotwaterheating + airconditioning + parking + furnishingstatus) +
  labs(title = "Średnie ceny nieruchomości w zależności od różnych kategorii",
       x = "Dostęp do drogi", y = "Średnia cena") +
  theme_minimal()
```


```{r}
# Utworzenie ramki danych zawierającej kolumny z ceną i kategoriami udogodnień
df <- data.frame(
  price = dane$price,
  mainroad = as.factor(dane$mainroad),
  prefarea = as.factor(dane$prefarea),
  basement = as.factor(dane$basement),
  hotwaterheating = as.factor(dane$hotwaterheating),
  airconditioning = as.factor(dane$airconditioning),
  parking = as.factor(dane$parking),
  furnishingstatus = as.factor(dane$furnishingstatus)
)

# Przy użyciu ggplot2
library(ggplot2)

ggplot(df, aes(x = interaction(mainroad, prefarea, basement, hotwaterheating, airconditioning, parking, furnishingstatus), y = price)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Zależność ceny od różnych udogodnień",
       x = "Udogodnienia",
       y = "Cena") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# za wiele nie widać na wykresach wspólnych ( dużo danych mało miejsca ) więc nie wiem czy nie lepiej zrobić to w oddzielnych

```
